export const FETCH_FROM_API = 'FETCH_FROM_API';
export const UPDATE_META_DATA = 'UPDATE_META_DATA';
export const UPDATE_GLOBAL_DEFAULTS = 'UPDATE_GLOBAL_DEFAULTS';
export const UPDATE_APP_SETTINGS = 'UPDATE_APP_SETTINGS';
export const SET_PAGE_SEO_CHECKS = 'SET_PAGE_SEO_CHECKS';
export const SET_PAGE_SEO_CHECK = 'SET_PAGE_SEO_CHECK';
export const SET_UNSAVED_META_SETTINGS = 'SET_UNSAVED_META_SETTINGS';
export const RESET_UNSAVED_META_SETTINGS = 'RESET_UNSAVED_META_SETTINGS';
export const SET_REFRESH_CALLED = 'SET_REFRESH_CALLED';
export const SET_CURRENT_POST_IGNORED_LIST = 'SET_CURRENT_POST_IGNORED_LIST';
export const SET_PAGE_SEO_CHECKS_BY_ID_AND_TYPE =
	'SET_PAGE_SEO_CHECKS_BY_ID_AND_TYPE';
export const SET_BATCH_PAGE_SEO_CHECKS = 'SET_BATCH_PAGE_SEO_CHECKS';
