export const SET_META_SETTINGS = 'SET_META_SETTINGS';
export const SET_META_SETTING = 'SET_META_SETTING';

export const SET_SITE_SETTINGS = 'SET_SITE_SETTINGS';
export const SET_SITE_SETTING = 'SET_SITE_SETTING';

export const FETCH_FROM_API = 'FETCH_FROM_API';

export const SET_LOADING = 'SET_LOADING';
export const SET_SAVING = 'SET_SAVING';
export const SET_MESSAGE = 'SET_MESSAGE';

export const TOGGLE_SITE_SELECTOR_MODAL = 'TOGGLE_SITE_SELECTOR_MODAL';
export const SET_CONFIRMATION_MODAL = 'SET_CONFIRMATION_MODAL';

export const SET_SEARCH_CONSOLE = 'SET_SEARCH_CONSOLE';

export const SET_SITE_SEO_ANALYSIS = 'SET_SITE_SEO_ANALYSIS';

export const SET_UNSAVED_SETTINGS = 'SET_UNSAVED_SETTINGS';
export const RESET_UNSAVED_SETTINGS = 'RESET_UNSAVED_SETTINGS';

export const SET_EMAIL_REPORTS_SETTINGS = 'SET_EMAIL_REPORTS_SETTINGS';
